version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  # job-service:
  #   build: ./job-service
  #   container_name: job-service
  #   environment:
  #     RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

  # worker-service:
  #   build: ./worker-service
  #   container_name: worker-service
  #   environment:
  #     RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq

volumes:
  rabbitmq_data:
